import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { dirname,resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const read=path=>readFile(resolve(root,path),'utf8');
const [worker,schema,html,feature,api,app,config,footer,sw,portalCss]=await Promise.all(['worker/index.js','worker/schema.sql','index.html','src/features/forecast-verification.js','src/services/weather-api.js','src/app.js','src/core/config.js','src/features/footer-social.js','service-worker.js','css/portal.css'].map(read));
for(const token of ['forecast_snapshots','captureForecastSnapshot','forecastVerification','/forecast-verification','temperatureMae','rainAccuracy','windMae'])assert.ok(worker.includes(token),`Verificació V22: falta ${token}`);
assert.ok(schema.includes('CREATE TABLE IF NOT EXISTS forecast_snapshots'));
assert.ok(html.includes('id="forecast-verification"')&&html.includes('data-portal-page="verificacio"')&&html.includes('Predicció vs realitat'));
assert.ok(!portalCss.includes(':not(.forecast-verification)'),'La verificació ja no s’ha de duplicar a la portada.');
assert.ok(app.includes("initWhenVisible('#forecast-verification'")&&app.includes('initPortal()'),'La pàgina de verificació ha de carregar les dades quan sigui visible.');
assert.ok(feature.includes('initForecastVerification')&&api.includes('fetchForecastVerification')&&app.includes('initForecastVerification'));
for(const token of ['socialCardHtml','socialCardUrl','publishAutomaticSocialDraft','/photos','sendPhoto','uploadBlob','publishThreads','graph.threads.net','threads_publish','THREADS_ACCESS_TOKEN','META_INSTAGRAM_IMAGE_URL'])assert.ok(token==='META_INSTAGRAM_IMAGE_URL'?!worker.includes(token):worker.includes(token),`Automatització V22: comprovació fallida ${token}`);
for(const token of ['recoverIncompleteDailySocialDraft','cacheEverything:false',"status IN ('approved','partially_published')",'ready=${attempt}-${Date.now()}'])assert.ok(worker.includes(token),`Recuperació social V22.5.1: falta ${token}`);
for(const network of ['threads','tiktok','whatsapp','youtube'])assert.ok(config.includes(`${network}:`)&&footer.includes(`['${network}'`),`Enllaç social V22 absent: ${network}`);
assert.ok(!config.includes("x:")&&!footer.includes("['x'"),'X no s’ha eliminat completament del directori social.');
assert.ok(sw.includes('/src/features/forecast-verification.js'));
console.log('Test V22: verificació real, targetes dinàmiques i xarxes correctes');
