import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { buildSlideSvg, datedKicker, editionLabel, shortDateLabel, weatherGlyph, weatherLabel, weatherTheme } from '../scripts/youtube-short.mjs';
import { projectRainPoint, rainColor, rainEvolutionFooter, rainFrameHours, rainMapContent, rainMapGrid } from '../scripts/youtube-rain-map.mjs';
import { sampleAt } from '../scripts/youtube-music.mjs';

assert.equal(weatherLabel(0),'Cel serè');
assert.equal(weatherLabel(1),'Poc ennuvolat');
assert.equal(weatherLabel(2),'Núvols i clarianes');
assert.equal(weatherLabel(3),'Cel cobert');
assert.equal(weatherLabel(61),'Pluja');
assert.equal(weatherLabel(95),'Tempesta');
assert.equal(weatherTheme(null).kind,'neutral');
assert.equal(weatherTheme(0).kind,'clear');
assert.equal(weatherTheme(61).kind,'rain');
assert.equal(weatherTheme(95).kind,'storm');
assert.doesNotMatch(weatherGlyph(0),/fill="#f1f8f5"/);
assert.match(weatherGlyph(61),/stroke="#66c7e8"/);
assert.match(weatherGlyph(95),/fill="#ffd166"/);
for(const code of [0,2,3,45,61,71,80,95]){
  const glyph=weatherGlyph(code);
  assert.match(glyph,/<rect x="-180" y="-180" width="360" height="360"/);
  assert.match(glyph,/transform="translate\(790 510\) scale\(1\)"/);
}
assert.equal(shortDateLabel('2026-09-01'),'DT 1 DE SETEMBRE');
assert.equal(datedKicker('Demà','2026-09-01'),'Demà · DT 1 DE SETEMBRE');
assert.equal(editionLabel('mati',new Date('2026-08-31T05:00:00.000Z')),'EDICIÓ MATÍ · 31 D’AGOST DEL 2026');
assert.equal(editionLabel('vespre',new Date('2026-08-31T18:30:00.000Z')),'EDICIÓ VESPRE · 31 D’AGOST DEL 2026');
const svg=buildSlideSvg({title:'Prova',kicker:'Avui · DL 31 D’AGOST',edition:'EDICIÓ MATÍ · 31 D’AGOST DEL 2026',content:'<text>24°</text>',footer:'Dades reals',weatherCode:61});
assert.match(svg,/width="1080" height="1920"/);
assert.match(svg,/METEO FONTANILLAS/);
assert.match(svg,/meteo\.fontanillas\.cat/);
assert.match(svg,/24°/);
assert.match(svg,/<title>Pluja<\/title>/);
assert.match(svg,/EDICIÓ MATÍ · 31 D’AGOST DEL 2026/);
assert.match(svg,/AVUI · DL 31 D’AGOST/);
assert.match(svg,/y="390"/);
assert.equal((svg.match(/y="1684"/g)||[]).length,6);
const observation=buildSlideSvg({title:'Dades reals',kicker:'Observació',content:'<text>19°</text>',footer:'Estació',weatherCode:null});
assert.doesNotMatch(observation,/<title>/);
const longObservation=buildSlideSvg({title:'Ara mateix, dades reals',kicker:'Observació',content:'',footer:'Estació',weatherCode:null});
assert.match(longObservation,/>Ara mateix, dades<\/text>/);
assert.match(longObservation,/>reals<\/text>/);
const trend=buildSlideSvg({title:'Tendència dels pròxims dies',kicker:'D’un cop d’ull',content:'',footer:'Web',weatherCode:0});
assert.match(trend,/>Tendència dels<\/text>/);
assert.match(trend,/>pròxims dies<\/text>/);
assert.doesNotMatch(trend,/pròxims…/);
const generator=await readFile(new URL('../scripts/youtube-short.mjs',import.meta.url),'utf8');
assert.doesNotMatch(generator,/\$\{weatherGlyph\(3,/);
assert.match(generator,/fetchRainEvolution/);
assert.match(generator,/rain-frame-/);
assert.match(generator,/LECTURA DE LES \$\{esc\(time\)\} H/);
assert.match(generator,/targetDate=dateLabel\(mainDay\.date\)/);
assert.deepEqual(rainFrameHours('mati'),[9,13,17,21]);
assert.deepEqual(rainFrameHours('vespre'),[6,12,18,23]);
assert.equal(rainMapGrid().length,64);
assert.equal(rainMapGrid()[0].name,'Sant Celoni');
assert.equal(rainColor(0).opacity,0);
assert.equal(rainColor(6).color,'#ffad42');
const projectedStation=projectRainPoint(rainMapGrid()[0]);
assert.ok(projectedStation.x>300&&projectedStation.x<420);
assert.ok(projectedStation.y>150&&projectedStation.y<260);
const rainPoints=rainMapGrid();
const rainEvolution={
  points:rainPoints,
  frames:[9,13,17,21].map((hour,index)=>({time:`2026-08-30T${String(hour).padStart(2,'0')}:00`,values:rainPoints.map((_,pointIndex)=>pointIndex===0?index*.4:(pointIndex+index)%7===0?2.4:0)})),
  source:'AROME France HD',sourceDetail:'model d’alta resolució · 1,5 km',spatial:true,
};
const rainSvg=rainMapContent(rainEvolution,2);
assert.match(rainSvg,/SANT CELONI/);
assert.match(rainSvg,/17:00 h/);
assert.match(rainSvg,/nord-est de Catalunya/);
assert.match(rainSvg,/feGaussianBlur/);
assert.match(rainSvg,/#d6cf45/);
assert.equal(rainEvolutionFooter(rainEvolution),'AROME HD via Open-Meteo · 1,5 km · orientatiu');
const workflow=await readFile(new URL('../.github/workflows/youtube-short-private.yml',import.meta.url),'utf8');
assert.match(workflow,/xfade=transition=fade/);
assert.match(workflow,/zoompan=/);
assert.match(workflow,/rain-frame-4\.png/);
assert.match(workflow,/-map 9:a/);
assert.match(workflow,/rsvg-convert -w 2160 -h 3840/);
assert.match(workflow,/-b:v 5M -minrate 5M -maxrate 5M/);
assert.match(workflow,/colorprim=bt709:transfer=bt709:colormatrix=bt709/);
assert.match(workflow,/-colorspace bt709 -color_primaries bt709 -color_trc bt709/);
assert.match(workflow,/-t 30 build\/youtube-short\/short\.mp4/);
assert.equal(sampleAt(0),0);
assert.ok(Math.abs(sampleAt(1.25))<=1);
assert.ok(Math.abs(sampleAt(12.5))>0.001);
assert.ok(Math.abs(sampleAt(28.5))>0.001);

console.log('Test del generador de Shorts: correcte');
